### ISSUE TITLE
Create breakdown of tasks and development documentation

### ISSUE THREAD

**Issue by owenwe** [pescCDS/cdsWebserver#4]
Need task list and documentation for developers to collaborate on project.

**Comment by jhamidi** [comment]
Hi Owen.  I thought working with github would be the same as any other repository.  We use svn.  It seems like the flow is quite different.  I added the egit plugin to my eclipse and I'm trying to learn it by creating the WebServicesInterfaceClient.java file under org/pesc/cds/webservice/v1_0 and committing it.  But I don't see it on github.  I used the "develop" branch, and I guess I need to create a pull request if I work in a branch?  What happens to these requests?  Who approves?  We should coordinate a method of working for all.

**Comment by owenwe** [comment]
Hmmm, it's been a while since I used svn. I'm not sure how the egit plugin
works.

Tim Calhoon has the ability to put users into the owners group, and I think
that group has the ability to merge pull requests. I see that you are
listed as one of the contributers, but I don't know if that means you can
merge pull requests. I do think that you have the ability to push and that
is pretty much what merging a pull request is.

I would recommend forking the pescCDS/cdsWebserver on your gitHub account
and working from that.

If you made commits to your local repo it won't show up in the remote repo
until you push to it. I'm writing documents on the project's wiki section
and one of them is about Git/GitHub:
https://github.com/pescCDS/cdsWebserver/wiki/Developer%20Documentation%20(Git%20GitHub)

So what I'm thinking is that every developer (contributor) should have a
gitHub account (they are free) and that they should fork the main project's
develop branch. Then when they complete their task, they push their local
develop branch to their remote fork, then do a pull request. I don't want
it to seem like this is "my" way, this is a common git development
approach. Each pull request allows anyone in the owners group to do a code
review and test the change prior to merging into the main project.

I'm open to discussion, let me know
Wes

**Comment by owenwe** [comment]
Initial tasks created.
